# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Create a local server from any location on your computer (soon you will be able to expose it to the Internet as well ;))"
  homepage "https://github.com/planta7/serve"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planta7/serve/releases/download/v0.1.5/serve_Darwin_arm64.tar.gz"
      sha256 "65fdc2d1ab4352fab0ea896f5280711afcc38534b2e63827682cf7f40afc141c"

      def install
        bin.install "serve"
        bash_completion.install "completions/serve.bash" => "serve"
        zsh_completion.install "completions/serve.zsh" => "_serve"
        fish_completion.install "completions/serve.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/serve/releases/download/v0.1.5/serve_Darwin_x86_64.tar.gz"
      sha256 "5b5d97d5ab4372974f683290c2e8c3e419619fd81a9bd7bc94b1acec02158343"

      def install
        bin.install "serve"
        bash_completion.install "completions/serve.bash" => "serve"
        zsh_completion.install "completions/serve.zsh" => "_serve"
        fish_completion.install "completions/serve.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/planta7/serve/releases/download/v0.1.5/serve_Linux_x86_64.tar.gz"
      sha256 "422d6a579bfce99b6a950e228b70bf2cd83aafbf248267bd855ca22ee6794e68"

      def install
        bin.install "serve"
        bash_completion.install "completions/serve.bash" => "serve"
        zsh_completion.install "completions/serve.zsh" => "_serve"
        fish_completion.install "completions/serve.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planta7/serve/releases/download/v0.1.5/serve_Linux_arm64.tar.gz"
      sha256 "39b3a2bb22f2a1ca9e5fffcc5f5b7c2745ae7e8be9f580f5dafdbb1ff1a3fb54"

      def install
        bin.install "serve"
        bash_completion.install "completions/serve.bash" => "serve"
        zsh_completion.install "completions/serve.zsh" => "_serve"
        fish_completion.install "completions/serve.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing serve!
    EOS
  end
end
