# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servant < Formula
  desc "Create a local server from any location on your computer, expose it to the Internet or keep it local (you can also use it to expose any server ;))"
  homepage "https://github.com/planta7/servant"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planta7/servant/releases/download/v0.4.2/servant_Darwin_x86_64.tar.gz"
      sha256 "c31b44c1acf27b6875e58578d529b12ba33a737e34e852da542b2e47f27062c0"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planta7/servant/releases/download/v0.4.2/servant_Darwin_arm64.tar.gz"
      sha256 "bf0c89a19a6b17c2add84ff2a8c1309d257c2f469261386d29674f81c894b329"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planta7/servant/releases/download/v0.4.2/servant_Linux_arm64.tar.gz"
      sha256 "d395f629677795ec5edd32f3799277d9e53a0840878f31232b3c59f2b79d8fc9"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/servant/releases/download/v0.4.2/servant_Linux_x86_64.tar.gz"
      sha256 "6d868d5fea9af04b8aa193017dd5517335ff7355963f24f6a54e052a088de4c7"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing servant!
    EOS
  end
end
