# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servant < Formula
  desc "Create a local server from any location on your computer (soon you will be able to expose it to the Internet as well ;))"
  homepage "https://github.com/planta7/servant"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planta7/servant/releases/download/v0.4.1/servant_Darwin_arm64.tar.gz"
      sha256 "cac651ba2ab7758c06b7d254cfead6f1b407c6fbda9ec0e281b7f392384a7d71"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/servant/releases/download/v0.4.1/servant_Darwin_x86_64.tar.gz"
      sha256 "58d4db398bfb041f873e488e38b0563d72c35b8d9ecb6d7ade978ad0dc6c2906"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planta7/servant/releases/download/v0.4.1/servant_Linux_arm64.tar.gz"
      sha256 "d37a1c6a1381970dd355d51a1f7d4e317591dafb85e5b48f60babac9812cd6fb"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/servant/releases/download/v0.4.1/servant_Linux_x86_64.tar.gz"
      sha256 "b6243dc7a81e1b3a6d5c5cd899c60226b25dac6cf1dd6553973f716c7ccd8e30"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing servant!
    EOS
  end
end
