# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servant < Formula
  desc "Create a local server from any location on your computer (soon you will be able to expose it to the Internet as well ;))"
  homepage "https://github.com/planta7/servant"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planta7/servant/releases/download/v0.4.0/servant_Darwin_arm64.tar.gz"
      sha256 "3f4471c9d93f0192c82acba806dcb91e27533de7ff8a8554c1e66901ce6b816d"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/servant/releases/download/v0.4.0/servant_Darwin_x86_64.tar.gz"
      sha256 "11676933e5eaf85e3a9e181fd6524070411850e2c542b1b5ea8569dcd1066524"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planta7/servant/releases/download/v0.4.0/servant_Linux_arm64.tar.gz"
      sha256 "338d4be4751b05aadd297d5e45ce565493a67a9e94cb674b2ec2f9e84863c74c"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/servant/releases/download/v0.4.0/servant_Linux_x86_64.tar.gz"
      sha256 "bd0bb4d1e8b43fa9e24db045b39846213263dd9ea1a515086e06f1dced7d6eed"

      def install
        bin.install "servant"
        bash_completion.install "completions/servant.bash" => "_servant"
        zsh_completion.install "completions/servant.zsh" => "_servant"
        fish_completion.install "completions/servant.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing servant!
    EOS
  end
end
