# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Create a local server from any location on your computer (soon you will be able to expose it to the Internet as well ;))"
  homepage "https://github.com/planta7/serve"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planta7/serve/releases/download/v0.1.4/serve_Darwin_arm64.tar.gz"
      sha256 "d9c0b8ec6b93b5006ce25fbfaef77048b84b560aa21e88ffb7c70be8c1ca1771"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/serve/releases/download/v0.1.4/serve_Darwin_x86_64.tar.gz"
      sha256 "aaa347e9875a38edf5c569b85d3ef2ada10dbf75d9f36a13edf915c42805d745"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planta7/serve/releases/download/v0.1.4/serve_Linux_arm64.tar.gz"
      sha256 "30c5605a6e8c0f43105f2a55df48ce1563fa7dabc636718838ea3329cca455cd"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/serve/releases/download/v0.1.4/serve_Linux_x86_64.tar.gz"
      sha256 "a014608f2627363792e66720240cac44ed57055be23804df08aa2d0db22fa594"

      def install
        bin.install "serve"
      end
    end
  end
end
