# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Create a local server from any location on your computer (soon you will be able to expose it to the Internet as well ;))"
  homepage "https://github.com/planta7/serve"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planta7/serve/releases/download/v0.1.0/serve_Darwin_x86_64.tar.gz"
      sha256 "57be697bb487b135940b1560722f0f60906536718a22567624da688179426b60"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planta7/serve/releases/download/v0.1.0/serve_Darwin_arm64.tar.gz"
      sha256 "cefb50a3838f1884b9dca7a2b8b1db4f82be76b323af1bc578d8e98af2ea6b7a"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planta7/serve/releases/download/v0.1.0/serve_Linux_arm64.tar.gz"
      sha256 "30267e12e44038119c0b22adcbef6d36815fc5e64b1364adb6796dac1de7698d"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planta7/serve/releases/download/v0.1.0/serve_Linux_x86_64.tar.gz"
      sha256 "26c957332a68dab8920cdbed77bfaca5801c8aa1da1cfa603a3fde5168f61167"

      def install
        bin.install "serve"
      end
    end
  end
end
